### ISSUE TITLE
kernal size

### ISSUE THREAD

**Issue by HaoGuo98** [f-dangel/unfoldNd#25]
Can i set kernal size like [1,3,3], it seems that this tool can only support the filter have same  dimmension.

**Comment by f-dangel** [comment]
Hi,

could you provide more details (e.g. which functionality you are trying to use, an exception the code runs into, a code example to showcase what you are trying to do)?

**Comment by HaoGuo98** [comment]
i want to use a filter with a size of [1,3,3]. but in the example, the kernel size  can just set a number not a triple?

**Comment by f-dangel** [comment]
That is because the [example](https://github.com/f-dangel/unfoldNd/blob/main/examples/example.py#L10-L11) uses 4d tensors (images), hence the kernel can have at most a two spatial dimensions. Also, they must be specified as `int` or `tuple`, as specified [here](https://pytorch.org/docs/stable/generated/torch.nn.Unfold.html#torch.nn.Unfold). I just ran the example with  `kernel_size = (1, 3)` and it seemed to work.

Let me know if this solves your problem.

**Comment by HaoGuo98** [comment]
Thanks! It works now, but for a input [1,64,2,256,256], filter size[64,64,1,3,3], the lib cost too much memory(64G)...

**Comment by HaoGuo98** [comment]
Thankes! It works now. However, compared with method in  https://discuss.pytorch.org/t/manual-implementation-of-unrolled-3d-convolutions/91021/3,  although the results have the same size, they are different.
![image](https://user-images.githubusercontent.com/42510628/119926461-0ee27600-bfaa-11eb-83b9-fa3f47f0d326.png)

**Comment by f-dangel** [comment]
Although there could be a bug in this lib, [this](https://discuss.pytorch.org/t/manual-implementation-of-unrolled-3d-convolutions/91021/5) message indicates that something could be wrong with your comparison implementation for `in_channels > 1`. Are the outputs still different if you set `in_channels = 1`? If so, can you provide an output of the mismatching values, or a script to reproduce the behavior?

**Comment by f-dangel** [comment]
Closing as stale.
